### ISSUE TITLE
Doesn't work on my Mackie DFX-12

### ISSUE THREAD

**Issue by Spetnik** [adamjezek98/x32_flappybird#1]
I tried everything, including loading the game on a USB stick and soldering the contacts to one end of an XLR cable (tried with phantom power both on and off).
I also tried printing the source code and stuffing the paper into the TRS jacks but that didn't work either.

Please add support for my analog mixer!

**Comment by adamjezek98** [comment]
Did you tried importing in into Reaper, and then playing it and using any ASIO card to senr that singal into channels 1 and 2?

**Comment by Spetnik** [comment]
Okay so I tried that and it sort of works. But if I raise any levels above unity my WiFi goes out.

**Comment by adamjezek98** [comment]
Glad to hear that, analog support was never planned, you should get a digital one for this.

**Comment by Spetnik** [comment]
Thanks! 
(Fyi this repo popped up in my Google feed. The fact that it suggested a 3-star repo and that I just happen to be both in the software development field and a fledgling audiophile is just a tad too creepy for my liking)
